export type PerguntasExcel = {
    Timestamp: string;
    "Email Address": string;
    "1. Qual o seu curso?": string;
    "2. Qual o período que cursa?": string;
    "3. Informe os 7 últimos dígitos do seu RA (109048xxxxxxx)": string;
    "4. Qual o estado do Brasil que você nasceu?": string;
    "5. Qual sua cidade de residência?": string;
    "6. Qual o seu gênero?": string;
    "7. Qual a sua data de nascimento?": string;
    "8. Qual é o seu estado civil?": string;
    "9. Você é portador de alguma necessidade especial?(Pode selecionar mais de uma, se for o caso)": string;
    "10. Você convive ou mora com alguma pessoa com deficiência?": string;
    "11. Quantos filhos você tem?": string;
    "12. Com quem você mora atualmente?": string;
    "13. Quantas pessoas, incluindo você, moram no seu domicílio?": string;
    "14. Qual a situação do domicílio onde mora?": string;
    "15. Tempo de moradia neste domicílio (Em anos)": string;
    "16. Qual a faixa de renda mensal da sua família (em Salários Mínimos)": string;
    "17.1. Quantas geladeiras há em seu domicílio.": string;
    "17.2. Quantos celulares comuns há em seu domicílio?": string;
    "17.3. Quantos micro-ondas há em seu domicílio?": string;
    "17.4. Quantos notebooks há em seu domicílio?": string;
    "17.5. Quantas máquinas de lavar roupa e(ou) tanquinho há em seu domicílio?": string;
    "17.6. Quantas motocicletas há em seu domicílio?": string;
    "17.7. Quantos automóveis há em seu domicílio?": string;
    "17.8. Quantos vídeos cassete e(ou) DVD players há em seu domicílio?": string;
    "17.9. Quantos televisores há em seu domicílio?": string;
    "17.10. Quantos smartphones há em seu domicílio?": string;
    "18. No seu domicílio tem?": string;
    "19.1. Você trabalha?": string;
    "19.2. Qual o seu vínculo com o emprego?": string;
    "19.3. Qual a área do seu trabalho?": string;
    "19.4. Qual seu horário de trabalho?": string;
    "19.5. Qual a empresa que você está contratado agora?": string;
    "20. Você tem plano de saúde privado?": string;
    "21.1. Qual o grau de escolaridade do seu pai?": string;
    "21.2. Qual o grau de escolaridade da sua mãe?": string;
    "22. Na sua vida escolar você estudou": string;
    "23.1. Com que frequência você utiliza microcomputadores?": string;
    "23.2. Onde você utiliza microcomputadores?": string;
    "23.3. Com qual finalidade você utiliza microcomputadores?": string;
    "24. Como você classifica seu conhecimento em informática": string;
    "25. Qual o seu conhecimento em relação aos aplicativos a seguir? [Windows]": string;
    "25. Qual o seu conhecimento em relação aos aplicativos a seguir? [Linux]": string;
    "25. Qual o seu conhecimento em relação aos aplicativos a seguir? [Editores de textos (Word, Writer, etc.)]": string;
    "25. Qual o seu conhecimento em relação aos aplicativos a seguir? [Planilhas eletrônicas (Excel, Calc, etc.)]": string;
    "25. Qual o seu conhecimento em relação aos aplicativos a seguir? [Apresentadores (Powerpoint, Impress, Prezzi, etc.)]": string;
    "25. Qual o seu conhecimento em relação aos aplicativos a seguir? [Sistemas de Gestão Empresaria]": string;
    "26. Agora, considere seu conhecimento sobre idiomas [Inglês]": string;
    "26. Agora, considere seu conhecimento sobre idiomas [Espanhol]": string;
    "26. Agora, considere seu conhecimento sobre idiomas [Outro Idioma]": string;
    "27. Considere a busca por informação nos seguintes meios de comunicação [Televisores]": string;
    "27. Considere a busca por informação nos seguintes meios de comunicação [Internet]": string;
    "27. Considere a busca por informação nos seguintes meios de comunicação [Revistas]": string;
    "27. Considere a busca por informação nos seguintes meios de comunicação [Jornais]": string;
    "27. Considere a busca por informação nos seguintes meios de comunicação [Rádio]": string;
    "27. Considere a busca por informação nos seguintes meios de comunicação [Redes socias]": string;
    "27. Considere a busca por informação nos seguintes meios de comunicação [Conversas com Amigos]": string;
    "28. Se você lê jornal, qual a frequência?": string;
    "29. Se você lê jornal, quais os assuntos que mais lê?": string;
    "30. Não considerando os livros escolares, quantos livros você lê por ano (em média)?": string;
    "31. Se você lê livros literários, qual/quais o(s) gênero(s) preferido(s)?": string;
    "32. Você dedica parte do seu tempo para atividades voluntárias?": string;
    "33. Qual religião você professa?": string;
    "34. Quais fontes de entretenimento cultural você usa?": string;
    "35. Estamos quase acabando... Como conheceu a FATEC Franca?": string;
    "36. Porque você escolheu este curso?": string;
    "37. Qual sua maior expectativa quanto ao curso?": string;
    "38. Qual sua expectativa após se formar?": string;
    "39. Você já estudou nesta escola?": string;
    "40. Você fez algum curso técnico?": string;
    "41. Qual o meio de transporte você usa para vir à escola?": string;
};
